/*
 * old
 */

CREATE TABLE LOGIN(
    USERID INT PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORDHASH VARCHAR(100) NOT NULL
);

CREATE TABLE ACCOUNT(
    ACCOUNTID INTEGER DEFAULT 1 NOT NULL PRIMARY KEY INCREMENT BY 1,
    USERID INTEGER REFERENCES LOGIN(USERID),
    PROVIDER VARCHAR(50),
    EMAIL VARCHAR(50),
    USERNAME VARCHAR(50),
    ACCOUNTPASSWORD VARCHAR(50),
    ADDITIONALINFORMATION VARCHAR(50),
    UNIQUENAME VARCHAR(50) UNIQUE
);

/*
 * new
 */

CREATE TABLE LOGIN(
    USERID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORDHASH VARCHAR(100) NOT NULL
);

CREATE TABLE ACCOUNT(
    ACCOUNTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERID INT REFERENCES LOGIN(USERID) NOT NULL,
    PROVIDER VARCHAR(100),
    UNIQUENAME VARCHAR(100),
    EMAIL VARCHAR(100),
    USERNAME VARCHAR(100),
    ACCOUNTPASSWORD VARCHAR(100),
    ADDITIONALINFORMATION VARCHAR(100)
);
